mode : "exact"
theme : "advanced"
language : "<%= I18n.locale.to_s.split('-')[0].downcase %>"
skin : "o2k7"
width : "594"
plugins : "safari,style,layer,table,advimage,inlinepopups,preview,contextmenu,paste,fullscreen,noneditable,visualchars,template"
cleanup : false

# Theme options
theme_advanced_buttons1 : "preview,|,styleselect,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor,|,bold,italic,underline,strikethrough,link,unlink"
#theme_advanced_buttons3 : "styleselect,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor"

theme_advanced_toolbar_location : "top"
theme_advanced_toolbar_align : "left"
theme_advanced_statusbar_location : "top"
theme_advanced_resizing : false
valid_elements : '*[*]'


